TRUNCATE TABLE 
  stock_movements, 
  sales, 
  budget_items, 
  budgets, 
  transaction_items, 
  transactions, 
  production_units,
  production_formulas,
  production_orders,
  maintenance_records,
  fuel_logs,
  fleet, 
  payroll, 
  time_logs,
  salary_advances,
  vacations,
  employees, 
  suppliers, 
  clients, 
  inventory_items,
  financial_accounts,
  tire_history,
  tires
RESTART IDENTITY CASCADE;
